dist: trusty
sudo: false

addons:
  postgresql: "9.6"

language: python

python:
  - 3.6

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings.travis
  - export DJCODE_SECRET_KEY 3247623963291291398732873287
  - export PYTHONPATH=$HOME/builds/wodo/WebTool3
  - export PIP_USE_MIRRORS=true
  - export DJCODE_DB_ENGINE=django.db.backends.postgresql
  - export DJCODE_DB_NAME=webtool
  - export DJCODE_DB_USER=travis
  - export DJCODE_DB_PASSWORD=
  - export DJCODE_DB_HOST=localhost
  - export DJCODE_DB_PORT=

install:
  - pip3 install -r requirements.txt

script:
  - createdb -O travis -E UTF8 --locale=de_DE.utf8 --template=template0 webtool
  - cd webtool
  - python3.6 manage.py migrate
