dist: trusty
sudo: false

addons:
  postgresql: "9.6"

language: python

python:
  - 3.6

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings.travis
  - export PYTHONPATH=$HOME/builds/wodo/WebTool3
  - export PIP_USE_MIRRORS=true

install:
  - pip3 install -r requirements.txt

script:
  - sudo -u postgres createdb -O travis -E UTF8 --locale=de_DE.utf8 webtool
  - cd webtool
  - python3.6 manage.py migrate
