language: python
python:
  - 3.6

services: postgresql

env:
  - DJANGO 1.11.2

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings.travis
  - export PYTHONPATH=$HOME/builds/wodo/WebTool3
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
