# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anniversary',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'name'), 'verbose_name': 'Gedenktag', 'verbose_name_plural': 'Gedenktage'},
        ),
        migrations.AlterModelOptions(
            name='approximate',
            options={'get_latest_by': 'updated', 'ordering': ('start_time',), 'verbose_name': 'Ungefährer Zeitpunkt', 'verbose_name_plural': 'Ungefähre Zeitpunkte'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'get_latest_by': 'updated', 'ordering': ('season__name',), 'verbose_name': 'Kalender', 'verbose_name_plural': 'Kalender'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'code', 'name'), 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='collective',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'name'), 'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'get_latest_by': 'updated', 'ordering': ('code',), 'verbose_name': 'Ausrüstung', 'verbose_name_plural': 'Ausrüstungen'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'updated', 'ordering': ('start_date',), 'verbose_name': 'Veranstaltungstermin', 'verbose_name_plural': 'Veranstaltungstermine'},
        ),
        migrations.AlterModelOptions(
            name='fitness',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'code'), 'verbose_name': 'Konditionelle Anforderung', 'verbose_name_plural': 'Konditionelle Anforderungen'},
        ),
        migrations.AlterModelOptions(
            name='fitnessdescription',
            options={'get_latest_by': 'updated', 'ordering': ('fitness__code', 'category__order'), 'verbose_name': 'Beschreibung der Konditionelle Anforderung', 'verbose_name_plural': 'Beschreibungen der Konditionelle Anforderungen'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'get_latest_by': 'updated', 'ordering': ('user__last_name', 'user__first_name'), 'verbose_name': 'Touren/Kurs/Gruppenleiter', 'verbose_name_plural': 'Touren/Kurs/Gruppenleiter'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'get_latest_by': 'updated', 'ordering': ('instruction__start_date', 'topic__order'), 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurse'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'name'), 'verbose_name': 'Abschnitt', 'verbose_name_plural': 'Abschnitte'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'updated', 'ordering': ('user__last_name', 'user__first_name'), 'verbose_name': 'Steckbrief', 'verbose_name_plural': 'Steckbriefe'},
        ),
        migrations.AlterModelOptions(
            name='retraining',
            options={'get_latest_by': 'updated', 'ordering': ['year', 'order'], 'verbose_name': 'Fortbildung', 'verbose_name_plural': 'Fortbildungen'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'get_latest_by': 'updated', 'ordering': ('name',), 'verbose_name': 'Saison', 'verbose_name_plural': 'Saisonen'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'name'), 'verbose_name': 'Unterabschnitt', 'verbose_name_plural': 'Unterabschnitte'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'get_latest_by': 'updated', 'ordering': ('collective__season__name', 'collective__name', 'session__start_date'), 'verbose_name': 'Gruppentermin', 'verbose_name_plural': 'Gruppentermine'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'code'), 'verbose_name': 'Technische Anforderung', 'verbose_name_plural': 'Technische Anforderungen'},
        ),
        migrations.AlterModelOptions(
            name='skilldescription',
            options={'get_latest_by': 'updated', 'ordering': ('skill__code', 'category__order'), 'verbose_name': 'Beschreibung der technischen Anforderung', 'verbose_name_plural': 'Beschreibung der technischen Anforderungen'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'name'), 'verbose_name': 'Bearbeitungsstand', 'verbose_name_plural': 'Bearbeitungsstände'},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'get_latest_by': 'updated', 'ordering': ('talk__start_date',), 'verbose_name': 'Vortrag', 'verbose_name_plural': 'Vortäge'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'updated', 'ordering': ('season__name', 'order', 'name'), 'verbose_name': 'Kursinhalt', 'verbose_name_plural': 'Kursinhalte'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'get_latest_by': 'updated', 'ordering': ('tour__start_date',), 'verbose_name': 'Gemeinschaftstour', 'verbose_name_plural': 'Gemeinschaftstouren'},
        ),
        migrations.AlterModelOptions(
            name='vacation',
            options={'get_latest_by': 'updated', 'ordering': ('start_date', 'name'), 'verbose_name': 'Ferien', 'verbose_name_plural': 'Ferien'},
        ),
        migrations.AddField(
            model_name='category',
            name='deadline',
            field=models.BooleanField(db_index=True, default=False, help_text='Kategorie für den Anmeldeschluss', verbose_name='Anmeldeschluss'),
        ),
        migrations.AddField(
            model_name='category',
            name='preliminary',
            field=models.BooleanField(db_index=True, default=False, help_text='Kategorie für die Vorbesprechung', verbose_name='Vorbesprechung'),
        ),
    ]
