# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20171020_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='event', serialize=False, to='server.Reference', verbose_name='Buchungscode'),
        ),
    ]
