# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 11:22
from __future__ import unicode_literals

from django.db import migrations
import server.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20171022_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='extra_charges_info',
            field=server.models.fields.InfoField(blank=True, default='', help_text='Welche weiteren Kosten kommen auf die Teilnehmer zu? z.B. Kosten für Seilbahn', max_length=75, verbose_name='Zusatzkosten'),
        ),
        migrations.AddField(
            model_name='tour',
            name='extra_charges_info',
            field=server.models.fields.InfoField(blank=True, default='', help_text='Welche weiteren Kosten kommen auf die Teilnehmer zu? z.B. Kosten für Seilbahn', max_length=75, verbose_name='Zusatzkosten'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='extra_charges',
            field=server.models.fields.AdmissionField(blank=True, decimal_places=2, default=0.0, help_text='Betrag in € für weiter Kosten', max_digits=6, verbose_name='Zusatzkosten'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='extra_charges',
            field=server.models.fields.AdmissionField(blank=True, decimal_places=2, default=0.0, help_text='Betrag in € für weiter Kosten', max_digits=6, verbose_name='Zusatzkosten'),
        ),
    ]
