# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20171031_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='equipments',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='session_list', to='server.Equipment', verbose_name='Ausrüstung'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='topic_list', serialize=False, to='server.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='equipments',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='topic_list', to='server.Equipment', verbose_name='Ausrüstung'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='equipments',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='tour_list', to='server.Equipment', verbose_name='Ausrüstung'),
        ),
    ]
