# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20171101_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='category_topic', serialize=False, to='server.Category', verbose_name='Kategorie'),
        ),
    ]
