# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20171101_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meeting',
            field=models.BooleanField(db_index=True, default=False, help_text='Kategorie für Kurstreffen Theorie/Praxis', verbose_name='Kurstermin'),
        ),
    ]
