# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_category_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collective',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='collective',
            name='id',
        ),
        migrations.AddField(
            model_name='collective',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='category_collective', serialize=False, to='server.Category', verbose_name='Kategorie'),
            preserve_default=False,
        ),
    ]
