# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20171101_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Markierung für Neue Veranstaltungen'),
        )
    ]
