# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 03:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import server.models.defaults


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20171111_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='prefix',
            field=models.PositiveSmallIntegerField(blank=True, default=server.models.defaults.get_default_prefix, validators=[django.core.validators.MaxValueValidator(9, 'Bitte keine Zahlen größer 9 eingeben')], verbose_name='Jahreszahl'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together=set([('season', 'category', 'prefix', 'reference')]),
        ),
    ]
