# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20171111_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='guide',
            field=models.ForeignKey(blank=True, default=None, help_text='Verantwortlich für Organisaton und Durchführung', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instruction_guides', to='server.Guide', verbose_name='Leitung'),
        ),
        migrations.AlterField(
            model_name='session',
            name='guide',
            field=models.ForeignKey(blank=True, default=None, help_text='Verantwortlich für Organisaton und Durchführung', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_guides', to='server.Guide', verbose_name='Leitung'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(blank=True, default=None, help_text='Verantwortlich für Organisaton und Durchführung', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tour_guides', to='server.Guide', verbose_name='Leitung'),
        ),
    ]
