# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import server.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20171111_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deprecated', models.BooleanField(default=False, verbose_name='Element gilt als gelöscht')),
                ('order', server.models.fields.OrderField(blank=True, db_index=True, default=0, help_text='Reihenfolge in der Druckausgabe', verbose_name='Reihenfolge')),
                ('description', server.models.fields.DescriptionField(blank=True, default='', help_text='Beschreibung der Veranstaltung und der geplanten Abläufe\nSonderzeichen: ● ○ ➘ ➚ „“ ½ ⅓ ⅔ ¼ ¾', verbose_name='Beschreibung')),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_list', to='server.Collective', verbose_name='Gruppe')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_list', to='server.Guide', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ('order', 'manager__user__last_name', 'manager__user__first_name'),
                'get_latest_by': 'updated',
            },
        ),
    ]
