# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collective',
            name='managers',
        ),
    ]
