# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_remove_collective_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='managers',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Ansprechpartner für die Gruppe', related_name='collectives', through='server.Role', to='server.Guide', verbose_name='Manager'),
        ),
    ]
