# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20171212_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='session_list', to='server.Category', verbose_name='Weitere Kategorien'),
        ),
        migrations.AddField(
            model_name='session',
            name='ladies_only',
            field=models.BooleanField(default=False, verbose_name='Von Frauen für Frauen'),
        ),
        migrations.AddField(
            model_name='session',
            name='misc_category',
            field=models.CharField(blank=True, default='', help_text='Kategoriebezeichnung, wenn unter Kategorie „Sonstiges“ gewählt wurde', max_length=75, verbose_name='Sonstiges'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_year',
            field=models.PositiveIntegerField(blank=True, default=2018, help_text='Jahr der Aufnahme in den AV', null=True, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.CharField(blank=True, default='', help_text='Name der/des Referenten', max_length=125, verbose_name='Referent'),
        ),
    ]
