# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20180102_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
