# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-01 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_auto_20180102_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='season',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='season',
        ),
        migrations.AlterField(
            model_name='topic',
            name='tariffs',
            field=models.ManyToManyField(db_index=True, related_name='tariff_list', to='server.Tariff', verbose_name='Preisaufschläge'),
        ),
    ]
