# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_instruction_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='special',
            new_name='is_special',
        ),
    ]
