# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 07:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_auto_20181211_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('deprecated', models.BooleanField(default=False, verbose_name='Element gilt als gelöscht')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), help_text='Welche Veranstaltungen kommen in das Booklet', size=None, verbose_name='Inhalt')),
                ('format', models.CharField(choices=[('desktop', 'Desktop'), ('desktop', 'Print')], default='desktop', help_text='Formatierungsvorgaben', max_length=10, verbose_name='Formatvorlage')),
                ('header', models.CharField(blank=True, default='', help_text='Das ist der Text für das Titelblatt', max_length=125, verbose_name='Titel')),
                ('sub_header', models.CharField(blank=True, default='', help_text='Das ist der Untertitel für das Titelblatt', max_length=125, verbose_name='Untertitel')),
                ('main_header', models.CharField(blank=True, default='', help_text='Das ist der Haupttitel für das Titelblatt', max_length=125, verbose_name='Haupttitel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('done', 'Done')], default='pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Programmheft',
                'verbose_name_plural': 'Programmhefte',
                'ordering': ('updated',),
                'get_latest_by': 'updated',
            },
        ),
    ]
