# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 12:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_booklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='format',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('print', 'Print')], default='desktop', help_text='Formatierungsvorgaben', max_length=10, verbose_name='Formatvorlage'),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='references',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), help_text='Welche Veranstaltungen kommen in das Booklet', size=1000, verbose_name='Inhalt'),
        ),
    ]
