# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-16 12:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_auto_20181211_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_id',
            field=models.CharField(help_text='Format:sss-oo-mmmmmm s=Sektionsnummer(008) o=Ortsgruppe(00|01) m=Mitgliedsnummer', max_length=13, null=True, unique=True, blank=True, validators=[django.core.validators.RegexValidator(re.compile('\\d{3}-\\d{2}-\\d{6}', 32), 'Bitte auf den richtigen Aufbau achten')], verbose_name='MitgliedsNr'),
        ),
    ]
