# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_auto_20181216_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_instruction', to='server.Category', verbose_name='Sonder Kategorie'),
        ),
    ]
