# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_tour_youth_on_tour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'updated', 'ordering': ('order', 'name'), 'verbose_name': 'Kursinhalt', 'verbose_name_plural': 'Kursinhalte'},
        ),
        migrations.AddField(
            model_name='event',
            name='reservation_service',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Reservierungswunsch für Schulungsraum'),
        ),
        migrations.AddField(
            model_name='event',
            name='shuttle_service',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Reservierungswunsch für AlpinShuttle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_year',
            field=models.PositiveIntegerField(blank=True, default=2019, help_text='Jahr der Aufnahme in den AV', null=True, verbose_name='Jahr'),
        ),
    ]
