# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_auto_20190525_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'get_latest_by': 'updated', 'ordering': ('user__last_name', 'user__first_name'), 'verbose_name': 'Tourenleiter', 'verbose_name_plural': 'Tourenleiter'},
        ),
        migrations.AlterModelOptions(
            name='userqualification',
            options={'ordering': ('year', 'qualification__order'), 'verbose_name': 'Trainer-Qualifikationen', 'verbose_name_plural': 'Trainer-Qualifikationen'},
        ),
        migrations.AddField(
            model_name='tour',
            name='relaxed',
            field=models.BooleanField(default=False, verbose_name='Gemütliche Tour'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_year',
            field=models.PositiveIntegerField(blank=True, default=2020, help_text='Jahr der Aufnahme in den AV', null=True, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tariffs',
            field=models.ManyToManyField(blank=True, db_index=True, default='', related_name='tariff_list', to='server.Tariff', verbose_name='Preisaufschläge'),
        ),
    ]
