# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-03-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0034_auto_20201221_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_year',
            field=models.PositiveIntegerField(blank=True, default=2021, help_text='Jahr der Aufnahme in den AV', null=True, verbose_name='Jahr'),
        ),
    ]
