# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-03-09 11:33
from __future__ import unicode_literals

from django.db import migrations
import server.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_auto_20210309_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationgroup',
            name='long_rate',
            field=server.models.fields.AdmissionField(blank=True, decimal_places=2, default=0.0, help_text='Abrechnungssatz für Kurstage länger 6 Stunden in €', max_digits=6, verbose_name='Abrechnungssatz für lange Kurstage'),
        ),
        migrations.AddField(
            model_name='qualificationgroup',
            name='middle_rate',
            field=server.models.fields.AdmissionField(blank=True, decimal_places=2, default=0.0, help_text='Abrechnungssatz für Kurstage länger als 3 Stunden und kürzer als 6 Stunden in €', max_digits=6, verbose_name='Abrechungssatz für mittlere Kurstage'),
        ),
        migrations.AddField(
            model_name='qualificationgroup',
            name='short_rate',
            field=server.models.fields.AdmissionField(blank=True, decimal_places=2, default=0.0, help_text='Abrechungssatz für Kurstage kürzer als 3 Stunden in €', max_digits=6, verbose_name='Abrechungssatz für kurze Kurstage'),
        ),
    ]
