# Generated by Django 2.2.24 on 2023-05-11 17:44

from django.db import migrations, models
import django.db.models.deletion
import server.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0036_auto_20210309_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userqualification',
            options={'get_latest_by': 'updated', 'ordering': ('year', 'qualification__order'), 'verbose_name': 'Trainer-Qualifikation', 'verbose_name_plural': 'Trainer-Qualifikationen'},
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='anniversary',
            name='public_holiday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Arbeitsfrei'),
        ),
        migrations.AlterField(
            model_name='approximate',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='Der initiale Zeitraum'),
        ),
        migrations.AlterField(
            model_name='approximate',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='category',
            name='climbing',
            field=models.BooleanField(blank=True, default=False, verbose_name='Klettersportart'),
        ),
        migrations.AlterField(
            model_name='category',
            name='collective',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Kategorie für Gruppentermine', verbose_name='Gruppentermine'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deadline',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Kategorie für den Anmeldeschluss', verbose_name='Anmeldeschluss'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meeting',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Kategorie für Kurstreffen Theorie/Praxis', verbose_name='Kurstermin'),
        ),
        migrations.AlterField(
            model_name='category',
            name='preliminary',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Kategorie für die Vorbesprechung', verbose_name='Vorbesprechung'),
        ),
        migrations.AlterField(
            model_name='category',
            name='summer',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Sommersportart'),
        ),
        migrations.AlterField(
            model_name='category',
            name='talk',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Kategorie für Vorträge', verbose_name='Vorträge'),
        ),
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Kategorie für Kurse', verbose_name='Kurse'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tour',
            field=models.BooleanField(blank=True, db_index=True, default=False, help_text='Kategorie für Touren', verbose_name='Touren'),
        ),
        migrations.AlterField(
            model_name='category',
            name='winter',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Wintersportart'),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='category_collective', serialize=False, to='server.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='internal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Interne Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='Die initiale Ausrüstung'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='event',
            name='distal',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Mit gemeinsamer Anreise'),
        ),
        migrations.AlterField(
            model_name='event',
            name='internal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Interne Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lea',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Low Emission Adventure'),
        ),
        migrations.AlterField(
            model_name='event',
            name='new',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Markierung für Neue Veranstaltungen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='public_transport',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Öffentliche Verkehrsmittel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reservation_service',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Reservierungswunsch für Schulungsraum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='shuttle_service',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Reservierungswunsch für AlpinShuttle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Je nach Abreisezeit wird eventuell Urlaub benötigt', null=True, verbose_name='Abreisezeit (Genau)'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='Die initiale konditionelle Anforderung'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='fitnessdescription',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='unknown',
            field=models.BooleanField(blank=True, default=False, help_text='Der unbekannte Guide', verbose_name='Unbekannt'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='equipment_service',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Reservierungswunsch für Ausrüstungsservice'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='is_special',
            field=models.BooleanField(blank=True, default=False, help_text='Kreative Kursinhalte', verbose_name='Spezialkurs'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='ladies_only',
            field=models.BooleanField(blank=True, default=False, verbose_name='Von Frauen für Frauen'),
        ),
        migrations.AlterField(
            model_name='part',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='integral_member',
            field=models.BooleanField(blank=True, default=False, verbose_name='A-Mitglied'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_year',
            field=models.PositiveIntegerField(blank=True, default=2023, help_text='Jahr der Aufnahme in den AV', null=True, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='qualificationgroup',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='qualificationgroup',
            name='long_rate',
            field=server.models.fields.AdmissionField(blank=True, decimal_places=2, default=0.0, help_text='Abrechnungssatz für Kurstage länger als 6 Stunden in €', max_digits=6, verbose_name='Abrechnungssatz für lange Kurstage'),
        ),
        migrations.AlterField(
            model_name='qualificationgroup',
            name='middle_rate',
            field=server.models.fields.AdmissionField(blank=True, decimal_places=2, default=0.0, help_text='Abrechnungssatz für Kurstage länger als 3 Stunden und kürzer als 6 Stunden in €', max_digits=6, verbose_name='Abrechnungssatz für mittlere Kurstage'),
        ),
        migrations.AlterField(
            model_name='qualificationgroup',
            name='short_rate',
            field=server.models.fields.AdmissionField(blank=True, decimal_places=2, default=0.0, help_text='Abrechnungssatz für Kurstage kürzer als 3 Stunden in €', max_digits=6, verbose_name='Abrechnungssatz für kurze Kurstage'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='retraining',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='retraining',
            name='qualification',
            field=models.ForeignKey(blank=True, help_text='Für fachspezifische Fortbildungen, die dazugehörige Qualifikation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_list', to='server.UserQualification', verbose_name='Qualifikation'),
        ),
        migrations.AlterField(
            model_name='role',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='season',
            name='current',
            field=models.BooleanField(blank=True, default=False, verbose_name='Die aktuelle Saison'),
        ),
        migrations.AlterField(
            model_name='season',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='section',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='session',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='session',
            name='equipment_service',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Reservierungswunsch für Ausrüstungsservice'),
        ),
        migrations.AlterField(
            model_name='session',
            name='speaker',
            field=models.CharField(blank=True, default='', help_text='Name der/des Referenten', max_length=125, null=True, verbose_name='Referent'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='Die initialen technische Anforderungen'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='skilldescription',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='state',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Der Bearbeitungsstand: "Ausgefallen"'),
        ),
        migrations.AlterField(
            model_name='state',
            name='default',
            field=models.BooleanField(blank=True, default=False, verbose_name='Der Bearbeitungsstand: "In Arbeit"'),
        ),
        migrations.AlterField(
            model_name='state',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='state',
            name='done',
            field=models.BooleanField(blank=True, default=False, verbose_name='Der Bearbeitungsstand: "Durchgeführt"'),
        ),
        migrations.AlterField(
            model_name='state',
            name='moved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Der Bearbeitungsstand: "Verschoben"'),
        ),
        migrations.AlterField(
            model_name='state',
            name='public',
            field=models.BooleanField(blank=True, default=False, verbose_name='Alle öffentlichen sichtbaren Bearbeitungsstände'),
        ),
        migrations.AlterField(
            model_name='state',
            name='unfeasible',
            field=models.BooleanField(blank=True, default=False, verbose_name='Der Bearbeitungsstand: "Noch nicht buchbar"'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Wieviel Teilnehemr können maximal teilnehmen', verbose_name='Max. Tln'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='equipment_service',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Reservierungswunsch für Ausrüstungsservice'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='internal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Interne Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='equipment_service',
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Reservierungswunsch für Ausrüstungsservice'),
        ),
        migrations.AlterField(
            model_name='userqualification',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='deprecated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Element gilt als gelöscht'),
        ),
    ]
