# Generated by Django 2.2.24 on 2023-05-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0037_auto_20230511_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='certificate',
            field=models.BooleanField(default=False, help_text='Der Zustand zur Sichtung des Führungszeugnis eines bestimmten Trainers', verbose_name='Führungszeugnis'),
        ),
    ]
