# Generated by Django 2.2.24 on 2023-05-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_guide_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='certificate_date',
            field=models.DateField(blank=True, default='', help_text='Das Datum der Sichtung des Führungszeugnis durch einen MA der GS', verbose_name='Datum der Sichtung des Führungszeugnis'),
        ),
    ]
