# Generated by Django 2.2.24 on 2023-05-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_guide_certificate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='mountain_bus',
            field=models.BooleanField(default=False, verbose_name='Bergbus'),
        ),
    ]
