# Generated by Django 2.2.24 on 2023-07-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_tour_mountain_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='kv_link',
            field=models.URLField(blank=True, default='', help_text='Link zum KV', verbose_name='KV-Link'),
        ),
        migrations.AddField(
            model_name='tour',
            name='kv_link',
            field=models.URLField(blank=True, default='', help_text='Link zum KV', verbose_name='KV-Link'),
        ),
    ]
