# Generated by Django 2.2.24 on 2023-08-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0043_auto_20230808_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='kv_link',
            field=models.URLField(blank=True, default='', help_text='Link zum KV', verbose_name='KV-Link'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='kv_link',
            field=models.URLField(blank=True, default='', help_text='Link zum KV', verbose_name='KV-Link'),
        ),
    ]
