# Generated by Django 2.2.24 on 2024-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0045_auto_20240226_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='certificate_required',
            field=models.BooleanField(default=False, help_text='Wird ein Führungszeugnis vom Guide benötigt oder nicht', verbose_name='Führungszeugnis benötigt'),
        ),
    ]
