# Generated by Django 2.2.24 on 2025-02-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0046_guide_certificate_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_year',
            field=models.PositiveIntegerField(blank=True, default=2025, help_text='Jahr der Aufnahme in den AV', null=True, verbose_name='Jahr'),
        ),
    ]
