# Generated by Django 2.2.24 on 2025-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0047_auto_20250212_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='contract_required',
            field=models.BooleanField(default=False, help_text='Ist ein Trainervertrag vom Guide unterzeichnet oder nicht', verbose_name='Trainervertrag benötigt'),
        ),
    ]
