# Generated by Django 2.2.24 on 2025-02-12 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0048_guide_contract_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='contract_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Das Datum des Unterzeichnen des Trainervertrags, eingetragen durch einen MA der GS', verbose_name='Datum der Unterschrift des Trainervertrags'),
        ),
    ]
